#!/bin/sh

WallDir=${1:-~/Pictures/Wallpapers}

PREVIEW=true \
rofi -no-config -theme fullscreen-preview.rasi \
	-show filebrowser -filebrowser-command 'swww img' \
	-filebrowser-directory "$WallDir" \
	-filebrowser-directories-first false\
	-filebrowser-sorting-method name \
	-selected-row 1 >/dev/null
